-- SELECT * FROM users;
-- DROP TABLE IF EXISTS users CASCADE;
-- DROP TABLE IF EXISTS categories;

TRUNCATE TABLE users RESTART IDENTITY CASCADE;
-- TRUNCATE TABLE user;
-- TRUNCATE TABLE categories;