-- SELECT * FROM users;
-- DROP TABLE IF EXISTS users CASCADE;
-- DROP TABLE IF EXISTS categories CASCADE;
-- DROP TABLE IF EXISTS budget;
-- DROP TABLE IF EXISTS weather;


-- DROP TABLE IF EXISTS categories;

-- TRUNCATE TABLE users RESTART IDENTITY CASCADE;
-- TRUNCATE TABLE categories RESTART IDENTITY CASCADE;
-- TRUNCATE TABLE budget;
-- TRUNCATE TABLE weather;

-- SELECT
-- b.*,
-- c.name AS category_name,
-- c.category_type
-- FROM budget AS b
-- LEFT JOIN categories AS c ON b.category_id = c.id
-- WHERE b.user_id = 1

-- SELECT MAX(reg_date) FROM weather WHERE id = '1'

-- SELECT * FROM weather
-- WHERE id='1' AND reg_date IN (SELECT MAX(reg_date) FROM weather WHERE id='1')
-- OR id='2nd-floor' AND reg_date IN (SELECT MAX(reg_date) FROM weather WHERE id='2nd-floor')
-- OR id='out-of-door' AND reg_date IN (SELECT MAX(reg_date) FROM weather WHERE id='out-of-door')

-- SUM by category type
-- SELECT SUM(value) FROM budget WHERE user_id = 1 AND (SELECT category_type FROM categories WHERE id = category_id) = 'expense';

-- Aggregate query. Sum by each category
-- SELECT c.name, SUM(value) AS total_value
-- FROM budget AS b
-- JOIN categories AS c ON b.category_id = c.id
-- WHERE b.user_id = 1
-- GROUP BY c.name
-- ORDER BY total_value DESC;

-- SELECT DISTINCT name
-- FROM budget
-- WHERE user_id = 1 AND name ILIKE '%fu%'


-- SELECT * FROM budget
-- ORDER BY id DESC
-- LIMIT 20;

-- DELETE FROM budget WHERE id = 8248;

INSERT INTO budget VALUES (DEFAULT, 31, 1, '2023-12-1', FALSE, DEFAULT, DEFAULT, 1, 1);
INSERT INTO budget VALUES (DEFAULT, 30, 1, '2023-12-1', FALSE, DEFAULT, DEFAULT, 1, 1);
INSERT INTO budget VALUES (DEFAULT, 29, 1, '2023-12-1', FALSE, DEFAULT, DEFAULT, 1, 1);
INSERT INTO budget VALUES (DEFAULT, 28, 1, '2023-12-1', FALSE, DEFAULT, DEFAULT, 1, 1);
INSERT INTO budget VALUES (DEFAULT, 27, 1, '2023-12-1', FALSE, DEFAULT, DEFAULT, 1, 1);
INSERT INTO budget VALUES (DEFAULT, 26, 1, '2023-12-1', FALSE, DEFAULT, DEFAULT, 1, 1);
INSERT INTO budget VALUES (DEFAULT, 25, 1, '2023-12-1', FALSE, DEFAULT, DEFAULT, 1, 1);
INSERT INTO budget VALUES (DEFAULT, 24, 1, '2023-12-1', FALSE, DEFAULT, DEFAULT, 1, 1);
INSERT INTO budget VALUES (DEFAULT, 23, 1, '2023-12-1', FALSE, DEFAULT, DEFAULT, 1, 1);
INSERT INTO budget VALUES (DEFAULT, 22, 1, '2023-12-1', FALSE, DEFAULT, DEFAULT, 1, 1);
INSERT INTO budget VALUES (DEFAULT, 21, 1, '2023-12-1', FALSE, DEFAULT, DEFAULT, 1, 1);
INSERT INTO budget VALUES (DEFAULT, 20, 1, '2023-12-1', FALSE, DEFAULT, DEFAULT, 1, 1);
INSERT INTO budget VALUES (DEFAULT, 19, 1, '2023-12-1', FALSE, DEFAULT, DEFAULT, 1, 1);
INSERT INTO budget VALUES (DEFAULT, 18, 1, '2023-12-1', FALSE, DEFAULT, DEFAULT, 1, 1);
INSERT INTO budget VALUES (DEFAULT, 17, 1, '2023-12-1', FALSE, DEFAULT, DEFAULT, 1, 1);
INSERT INTO budget VALUES (DEFAULT, 16, 1, '2023-12-1', FALSE, DEFAULT, DEFAULT, 1, 1);
INSERT INTO budget VALUES (DEFAULT, 15, 1, '2023-12-1', FALSE, DEFAULT, DEFAULT, 1, 1);
INSERT INTO budget VALUES (DEFAULT, 14, 1, '2023-12-1', FALSE, DEFAULT, DEFAULT, 1, 1);
INSERT INTO budget VALUES (DEFAULT, 13, 1, '2023-12-1', FALSE, DEFAULT, DEFAULT, 1, 1);
INSERT INTO budget VALUES (DEFAULT, 12, 1, '2023-12-1', FALSE, DEFAULT, DEFAULT, 1, 1);
INSERT INTO budget VALUES (DEFAULT, 11, 1, '2023-12-1', FALSE, DEFAULT, DEFAULT, 1, 1);
INSERT INTO budget VALUES (DEFAULT, 10, 1, '2023-12-1', FALSE, DEFAULT, DEFAULT, 1, 1);
INSERT INTO budget VALUES (DEFAULT, 9, 1, '2023-12-1', FALSE, DEFAULT, DEFAULT, 1, 1);
INSERT INTO budget VALUES (DEFAULT, 8, 1, '2023-12-1', FALSE, DEFAULT, DEFAULT, 1, 1);
INSERT INTO budget VALUES (DEFAULT, 7, 1, '2023-12-1', FALSE, DEFAULT, DEFAULT, 1, 1);
INSERT INTO budget VALUES (DEFAULT, 6, 1, '2023-12-1', FALSE, DEFAULT, DEFAULT, 1, 1);
INSERT INTO budget VALUES (DEFAULT, 5, 1, '2023-12-1', FALSE, DEFAULT, DEFAULT, 1, 1);
INSERT INTO budget VALUES (DEFAULT, 4, 1, '2023-12-1', FALSE, DEFAULT, DEFAULT, 1, 1);
INSERT INTO budget VALUES (DEFAULT, 3, 1, '2023-12-1', FALSE, DEFAULT, DEFAULT, 1, 1);
INSERT INTO budget VALUES (DEFAULT, 2, 1, '2023-12-1', FALSE, DEFAULT, DEFAULT, 1, 1);
INSERT INTO budget VALUES (DEFAULT, 1, 1, '2023-12-1', FALSE, DEFAULT, DEFAULT, 1, 1);