version: '3.9'

services:
  db:
    image: postgres
    ports:
      - '3432:5432'
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: admin
      POSTGRES_DB: budget
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data:
