export enum ResCodes {
  ERORR,
  VALIDATION_ERROR,
  CREATE_USER,
  LOGIN,
  SEND_RESTORE_PASSWORD_EMAIL,
  RESET_PASSWORD,
  SEND_USER,
  UPDATE_USER,
  DELETE_USER,
  CREATE_CATEGORY,
  GET_CATEGORIES,
  UPDATE_CATEGORY,
  DELETE_CATEGORY
}

export enum LogType {
  INCOME = 'income',
  EXPENSE = 'expense'
}
